### ISSUE TITLE
[Admin] Séparation des fichiers JS et CSS

### ISSUE THREAD

**Issue by BoboTiG** [BlogoText/blogotext#168]
Est-ce que ça vaut le coup de n'inclure que les script et fichiers de style en relation avec la page courante ?

**Comment by remrem** [comment]
ça ne me semble pas nécessaire
style.css.php fait 18Ko (+-)
javascript.js fait 62Ko (+-)
l'index de l'admin ne pèse que 160Ko (+-) et on est a - de 10 requêtes http.

C'est très bien comme ça, si tu veux optimiser de ce côté là, je pencherai plus pour :
- les compresser et mettre du `style.min.css` et `javascript.min.js` pour la prod.
- ajouter un système de versionning basée sur la version de BT, en ajoutant `?v=BT_VERSION` comme ça en cas d'update de BT, l'utilisateur n'aura pas de problème de cache (faudrait y penser à ça).

**Comment by BoboTiG** [comment]
Va pour le système de versionning, c'est pas grand chose à modif.

**Comment by BoboTiG** [comment]
Par contre, pour le JS, faudra revoir ça. Il est inclus sur chaque page, faudrait voir pour déplacer l'inclusion dans `tpl_get_footer()` et passer une variable `$js` contenant le code JS supplémentaire.

**Comment by B4rb3rouss** [comment]
J'aimai bien lidée des .min.css et .min.js, c'est bon pour les auto-hébergés. C'est trop de boulot à maintenir ?

**Comment by BoboTiG** [comment]
Non, c'est tout à fait faisable. À faire à la fin de la période de freeze. 

-- 
Mickaël Schoentgen
http://www.tiger-222.fr

**Comment by remrem** [comment]
Pour les manipulations du JS, on repousserai pas ça la v4 ? Histoire de faire tout le refacto process/html en même temps ?

**Comment by BoboTiG** [comment]
Yes, we can!

-- 
Mickaël Schoentgen
http://www.tiger-222.fr

**Comment by remrem** [comment]
[TROLL] @BoboTiG Tu veux dire "Make America Great Again!" ? [/TROLL]

**Comment by remrem** [comment]
Je suis dessus [4.0].
Au menu : 
- réorganisation des fichiers du template admin
- ajout d'un cache (php et header) pour la partie CSS
- gestion automatique du cache en fonction de la version/dev mode
- compression des caches JS/CSS

En gros, si BT est une version de dev, pas de cache, si BT est en prod, création du cache pour la version en cours. Pas de noeud au cerveau à se faire ;)
