### ISSUE TITLE
Freeze pour la version 3.7

### ISSUE THREAD

**Issue by BoboTiG** [BlogoText/blogotext#178]
Hop, la 3.7 est _freezée_ !

Rapportez toute erreur éventuelle sur cette issue.

---

Quelques commits ne rentrant pas en compte dans le processus de nettoyage :
- 2880b1eb86e8849365618cf7454a92ffe07dabfe articles : les images sont redimensionnées comme il faut dans l'aperçu
- 57bb5e5dcd62e2c2b6de1985a1914345e7fb2725 fichiers : ajout d'une icône pour les ebooks (`epub` et `mobi`) et prise en charge du conteneur vidéo `mkv`
- c7f7dba0bc66fb587aae91ba29441563315adc06 fichiers : la suppression d'un fichier bloquait quand il n'y avait pas d'image
- 105beebd1343331dcfa4eab59ce88d085abdbe96 fichiers : déplacement de `$GLOBALS['files_ext']` dans filesystem.php
- bf99ff8f5f0d0ef42bf1767c32f4c5168a4b6582 auth, install : meilleur hashage du mot de passe utilisateur (la limite des 72 caractères est levée et on gagne en sécurité), fix #132 
- 936a10b0cfa4c1279c2df2c52192721ae2ee7a7f : auth, install : autofocus sur le champ texte approprié
- 44ae00d348ab4eaf588d7702bfa0058089c1efaa : auth : ajout du mot clef `required` pour les champs d'identification et changement de syntaxe des lignes ajoutées au fichiers d'authentification

**Comment by BoboTiG** [comment]
Bug : admin > Flux RSS, il y a une erreur JS qui empêche de marquer tous les flux visibles comme lu. Je laisse de côté, en attendant si @remrem tu veux t'y coller, pas de soucis.

**Comment by remrem** [comment]
ça ne sera pas avant ce W.E. pour ma part :/

**Comment by BoboTiG** [comment]
Il manque une constante `URL_BACKUP` pour l'export des données. Actuellement, on utilise `DIR_BACKUP` mais les liens sont erronés. Chaque dossier de backup se trouvera dans son vhost pour la v4, en attendant je zappe et utilise `URL_ROOT`.

**Comment by BoboTiG** [comment]
Bon, je n'aurai pas le temps d'en faire plus avant la semaine prochaine. Ce qu'il reste à faire :
1. Tester l'import WordPress (tout le reste est OK).
2. Tester les addons correctement.

@remrem tu peux repasser sur la partie admin, je passerai sur la partie public la semaine pro.

**Comment by remrem** [comment]
@BoboTiG ok

**Comment by remrem** [comment]
première passe sur admin/feed
 - dirty fix pour "mark as read" par flux
 - dirty fix pour "mark as read" et l'affichage de flux par "folder"
+ quelques modifications (ça relave du détail)

**Comment by BoboTiG** [comment]
Ça règle en partie le problème. Il reste ce scénario qui bloque : quand tu sélectionnes sur "Tous les flux" et que là tu cliques sur l'icône pour tout marquer comme lu => erreur JS.

**Comment by remrem** [comment]
- le fix pour tous les flux est prêt.
- premiers test sur l'import WP, semble ok.
Je commit tout à l'heure

**Comment by remrem** [comment]
#181 
- fix pour "mark as read" pour "tous les flux"
- fix d'un bug pour les boutons d'action des addon
- fix dans admin/auth à propos des arguments de fonctions
cf. http://php.net/manual/fr/functions.arguments.php#functions.arguments.type-declaration

**Comment by BoboTiG** [comment]
J'ai supprimé les fonctions inutilisées, dis moi si ça te convient, sinon je revert. Pour info, j'ai utilisé cette commande :

    egrep -rhio 'function .+\(' *.php admin inc | awk -F'[( ]' '{print "echo -n " $2 " && grep -rin " $2 " *.php admin inc | grep -v function | wc -l"}' | bash | egrep '[^0-9]0$'

**Comment by remrem** [comment]
hormis pour la function str2() qui est utilisée dans l'addon calendar, ça me semble bon ;)

**Comment by BoboTiG** [comment]
Je mettrai à jour l'addon. D'ailleurs, je n'ai absolument pas vérifié les addons, à ne pas oublier.

**Comment by remrem** [comment]
#188 ajout d'un script pour l'update
Procédure de mise à jour : 
1. sauvegarder BDD + config (une copie en laissant les originaux)
2. supprimer les dossiers      
   - addons/
   - admin/
   - cache/
   - inc/ 
3. claquer la version 3.7-dev de BT
4. rendez-vous sur http://example.com/admin/install.php et suivez la procédure
5. vérifier la partie public et admin afin de vérifier qu'il n'y ai pas de message d'erreur ou de contenu disparu

Pour info, durant la procédure, BT doit vous demander de spécifier un utilisateur, c'est normal étant donné que le process de hashage des mots de passes change avec la 3.7 (sans rétrocompatibilité).

En cas d'échec : 
1. réinstaller BT master, remettre vos sauvegardes (BDD + config)
2. venir nous le signaler sur github en étant le plus précis possible dans la description des problèmes rencontrés.

**Comment by BoboTiG** [comment]
Ça me semble pas mal du tout :)

Je corrige 2-3 choses et devrait être pas mal.

**Comment by B4rb3rouss** [comment]
Dans le thème par défaut, on a dans les liens de navigation : 
- Lien "à propos" qui redirige vers une ancre vide
- Titre "Trouver un article" qui contenait avant le module calendrier, actuellement vide car aucun module n'est activé par défaut

Après la publication d'un article, le lien "Partager" (à côté de "voir en ligne") ne fonctionne pas semble-t-il. Rien n'est proposé actuellement, ça affiche juste l'article.

C'est tout ce que j'ai vu pour l'instant.

Question à réfléchir : y a -t-il des changements à annoncer pour la mise à jour d'une instance du blog (thème...) ?

**Comment by remrem** [comment]
Pour le template "à propos" et l'intitulé du calendar, à voir avec @BoboTiG, mais bien vu ;)

Pour le changelogs, yep, pas mal de choses, on avait discuté avec @BoboTiG de mettre en place un changelog.txt (ou dans ce style), je crois que je vais m'y atteler demain (vu que la 3.7 est repoussée).

**Comment by remrem** [comment]
> Après la publication d'un article, le lien "Partager" (à côté de "voir en ligne") ne fonctionne pas semble-t-il. Rien n'est proposé actuellement, ça affiche juste l'article.

La fonction de partage, il me semble que c'est pour les articles non publiés (invisible ou date de publication > date actuelle) ça ajoute un paramètre share (`&share`) à la fin de l'url qui permet de donner l’accès à un article. Il y a un autre comportement attendu ou différent dans les versions précédentes de BT ?

**Comment by B4rb3rouss** [comment]
Ok pour le partage, j'avais pensé à un truc du type "partager sur facebook" et autres bêtises du genre. Mais si c'est pour faire lire le brouillon c'est top. Il faut changer peut-être l'intitulé dans ce cas ?

**Comment by remrem** [comment]
Yep, l'intitulé actuel peux prété à confusion, je te rejoins pour le changer.    
Pour les médias sociaux, un addon serait plus adapté ;)

**Comment by B4rb3rouss** [comment]
+1 pour l'addon, j'ai commencé un truc inspiré de pluxml, mais j'attends la sortie de la 3.7 pour m'y replonger.

**Comment by remrem** [comment]
Pour les addons, tu peux t'y mettre, la 3.7 est freezée, donc plus de bouleversements, juste du debug et de du peaufinage ;)

**Comment by B4rb3rouss** [comment]
Question bête : la 3.7 reste en freeze jusqu'à une date limite ?

**Comment by remrem** [comment]
@B4rb3rouss , yep, elle est même dépassée, malheureusement @BoboTiG a certains impératifs à gérer IRL, donc la 3.7 est en stand by.
Tu as pu la tester ? (branch dev)

**Comment by B4rb3rouss** [comment]
yep, j'ai pas mal testé, importé mon ancien blogotext et n'ai rien remarqué de particulier. J'hésite à passer en prod' mais rien ne presse après tout :) .
Et puisque je vois tes commits sur la 4.0 ça donne encore plus envie.

J'aurais un peu de temps bientôt pour me replonger dans les plugins, ça sera peut-être l'occasion de reprendre la 3.7.

**Comment by remrem** [comment]
Cool, merci pour le retour.
Pour passe en prod, si tu n'es pas pressé, vaux mieux attendre la release 3.7.
Yep, la 4.0 promets, mais la 3.7 bouscule pas mal de choses ;)

**Comment by B4rb3rouss** [comment]
J'ai refait une migration ce matin et j'ai remarqué que lors de l'export du blog pour l'importer ensuite, les paramètres "Nom de l'auteur, du site, description..." n'étaient pas exportés. Rien d'étonnant lorsqu'on voit le code mais il faudra penser à l'expliquer dans les notes de mises à jour.

Sinon, fonctionnent très bien : 
- L'importation du fichier .json
- L'exportation du .zip avec images et base de données. Il faut toutefois l'extraire à la main, car pas d'importation possible.

**Comment by remrem** [comment]
@B4rb3rouss , je jette un coup d'oeil, mais pour la migration, pas besoin d'exporter/importer.
La procédure https://github.com/BoboTiG/blogotext/issues/178#issuecomment-268914694

**Comment by B4rb3rouss** [comment]
Non en effet, pas besoin d'export/import pour la migration, mais c'était par habitude.

**Comment by B4rb3rouss** [comment]
D'autres remarques suite à des tests approfondis, dans le fichier list.html

- Le ``{includes.js}`` rajoute un ``;`` à la fin de chaque appel de scripts
- Le ``        <meta name="description" content="{article_chapo}" />`` génère un contenu invalide pour ce header, il faudrait "nettoyer" le contenu.

**Comment by remrem** [comment]
Si tu veux un coup de main pour les correctifs, n'hésite pas...

**Comment by B4rb3rouss** [comment]
pour le ``meta name=*`` je veux bien.
Sinon c'est bon pour ``includes.js`` et je m'occupe des avatars en soirée.

**Comment by remrem** [comment]
@B4rb3rouss ok, je m'occupe de la `<meta />`

**Comment by B4rb3rouss** [comment]
C'est bon pour moi, j'ai fait les 2 PR.

Pour ``<meta />`` je te laisse la main car ne suis pas sûr de moi. Il faudrait échapper tous les éléments xml du texte qui ne sont pas valides.

**Comment by B4rb3rouss** [comment]
Nouveau "bug" lorsqu'on renomme le dossier admin : il persiste à vouloir trouver les libs dans /admin : 


```
Warning: require_once(/htdocs/yeuxdelibad.net/Ignore/php/blogotext/admin/inc/lang/fr_fr.php): failed to open stream: No such file or directory in /htdocs/yeuxdelibad.net/Ignore/php/blogotext/inc/util.php on line 263

Fatal error: require_once(): Failed opening required '/htdocs/yeuxdelibad.net/Ignore/php/blogotext/admin/inc/lang/fr_fr.php' (include_path='.:/pear/lib:/var/www/pear/lib') in /htdocs/yeuxdelibad.net/Ignore/php/blogotext/inc/util.php on line 263
```

**Comment by remrem** [comment]
héhé, my bad pour le coup du path admin, j'ai vu ça en bossant sur la v4, mais j'ai oublié de fix la 3.7 :s
Je PR un fix tout à l'heure...

**Comment by remrem** [comment]
pour l'admin path, le #210 doit fixer le problème ;)

**Comment by B4rb3rouss** [comment]
Vu, merci !

Rien de tel qu d'installer la 3.7-dev pendant quelques jours pour chasser les bugs. Il va avoir du boulot @BoboTiG à son retour ^^

**Comment by B4rb3rouss** [comment]
@remrem : testé. Ça semble fonctionner comme prévu.

**Comment by remrem** [comment]
Retour au freeze de la 3.7, je teste de mon côté la stabilité, je cherche les quelques bugs et on la pousse en prod.
Tous retours, tests sont les biens venus ;)

**Comment by B4rb3rouss** [comment]
J'utilise en prod la 3.7 depuis un moment pour l'instant, et mis à part les flèches de navigation dans le lecteur de flux, rien à redire.

**Comment by remrem** [comment]
ok, je vois ça...

**Comment by B4rb3rouss** [comment]
J'ai mal dû m'exprimer, ça a été réglé dans un précédent commit.

**Comment by remrem** [comment]
oki ;)
derniers tests et je pousse en prod ;)

**Comment by remrem** [comment]
Je revois le dossier addon du repos blogotext, je vais juste mettre un dossier basique avec une note dedans.
