### ISSUE TITLE
wallabag-like

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#223]
Salut !
Une idée comme ça... Actuellement dans le lecteur de flux, on peut "tagguer" un article comme "favori" afin de le retrouver facilement ensuite.
Cependant, si je ne dis pas de bêtises, l'article n'est pas sauvegardé sur le serveur comme le ferait wallabag.
Ça me semble intéressant de pouvoir garder une copie d'un article un peu comme le fait wallabag.

Sinon, l'idéal serait pouvoir d'ajouter une petit icône qui permet de relier et ajouter en un clic l'article à une instance de wallabag.

**Comment by remrem** [comment]
à vérifier, mais il me semble que wallabag propose une api, soit doit être faisable assez facilement.
Je pense que l'idéal serait de passer par un addon (en mettant en place des hook partie admin).

**Comment by remrem** [comment]
à voir ce que @BoboTiG en pense...

**Comment by remrem** [comment]
On pousse vers la 4.X, le temps de voir si on pousse ça en tant que addon ...

**Comment by B4rb3rouss** [comment]
On peut fermer, non?

**Comment by remrem** [comment]
yep
