### ISSUE TITLE
[ADMIN][addon] Menu déroulant

### ISSUE THREAD

**Issue by Starsheep08** [BlogoText/blogotext#232]
Bonjour !
Petit détail mais qui nuit à l'ergonomie, rien n'indique que l'on peut avoir plus d'informations sur un addon lorsque l'on clique dessus. Je suis certainement un boulet, mais sans aide, je ne m'en serai jamais rendu compte. ;)
Serait-il possible d'ajouter une petite flèche vers le bas à droite du numéro de version ?

Exemple du style: 
```
---------------------------------------------------------------------------------
| Nom de l'addon                                                 1.0          v |
---------------------------------------------------------------------------------
```

Merci ! :)

**Comment by remrem** [comment]
+1 (pour la faute en matière d'ergonomie, pas pour l'aspect boulet ;) )
@BoboTiG , pas d'objection ?

**Comment by Starsheep08** [comment]
Quel rapide ce Thuban alors. :D

**Comment by remrem** [comment]
Ça m'a l'air tout bon, je clôture cette issue. En cas de problème, il faudra en créer une autre. ;)
