### ISSUE TITLE
[NEWS] A propos de BlogoText

### ISSUE THREAD

**Issue by remrem** [BlogoText/blogotext#238]
## Good news everyone !
BlogoText vit toujours et évolue \o/ 

La vie étant ce qu'elle est et chacun ayant des impératifs IRL (famille, boulot ...), le temps vient parfois à manquer, d'où, entres autres raisons, les changements de mainteneurs concernant BlogoText (... @timovn, @BoboTiG ). Ce n'est pas trop un problème en soi, chaque mainteneurs (et aussi les contributeurs !) a apporté sa pierre à l'édifice et a permis de faire vivre et évoluer BlogoText.

Aujourd'hui, BlogoText avance encore et toujours dans le bon sens.

### Qu'est-ce qui change ?
- le projet est dorénavant rattaché à une organisation (sur GitHub), ainsi, peu importe le ou les mainteneurs, BlogoText aura sa propre "identité", URL...
- le projet sera maintenu par un ou plusieurs mainteneurs afin d'assurer au maximum la continuité et l'évolution du projet, selon les disponibilités de chacun.
- pour le reste, pas grand chose, les contributeurs sont toujours appréciés et les bienvenus ;)

Merci aux mainteneurs, aux contributeurs et aux utilisateurs.
Cap sur la 3.7 !

**Comment by B4rb3rouss** [comment]
Ça y est, c'est officiel, la 3.7 est en route ? :)

**Comment by remrem** [comment]
Je passe un coup de polish, je modifie 2 ou 3 variables et je la passe en prod demain ;)

**Comment by Starsheep08** [comment]
Ouh ça bouge ici. :)

Ça va "adminsyser" sévère dans les jours qui viennent. :)

**Comment by remrem** [comment]
@B4rb3rouss @BoboTiG @Starsheep08 ...

J'ai release la 3.7.0 à l'instant : https://github.com/BlogoText/blogotext/releases/

Merci à tous ;)
P.S. petit teaser, je vais faire une autre annonce (une bonne) concernant BlogoText, très probablement ce week end ... :D

**Comment by Starsheep08** [comment]
Salut !

Mise à jour passée avec succès.

Une autre annonce ? En plus d'une release ? oO Une 4.0 ? :p 

Et sinon je ne connais pas assez git pour t'aider... :/

**Comment by Starsheep08** [comment]
Ah et j'ai oublié le principal.

Félicitations à tous pour cet énorme travail. :)

**Comment by BoboTiG** [comment]
Congrats :)
Pour le coup de la seule PR, c'est un peu dommage. Comment as-tu fait exactement ? On peut voir pour faire un rebase.

**Comment by remrem** [comment]
bah ... comme un bourrin, PR dev > master, validé, ok ...
Si par rebase tu parles de changer la branche principale de master à dev, yep, j'y ai pensé et je pense que ça peux être la bonne solution (quelques trucs à mettre en place pour faire propre...)

**Comment by remrem** [comment]
Et congrats à toi ;) , c'est quand même toi qui a porté le truc, en fin de compte je ne fais qu'appuyer sur le bouton à la fin ;)

**Comment by remrem** [comment]
@BoboTiG , je crois que j'ai réussi à corriger le tir, il a l'air d'avoir pris en compte tous les commits (pt de vue stats en tout cas)...

**Comment by BoboTiG** [comment]
Nickel comme ça :)

**Comment by remrem** [comment]
[WIP] https://blogotext.org

**Comment by B4rb3rouss** [comment]
Génial !
Et la 3.7.1 qui montre le bout de son nez. Merci !

**Comment by remrem** [comment]
[3.7.1](https://github.com/BlogoText/blogotext/releases/tag/3.7.1) Disponible ;)

[Sur le blog](https://blogotext.org/blog/?d=2017/04/19/10/19/46-blogotext-version-371-disponible), toutes critiques sont les bienvenues ;)

**Comment by B4rb3rouss** [comment]
Beau travail :)

Quelques remarques maintenant à propos du blog : 
- Les liens en en-tête sont collés, c'est dommage.
![](https://framapic.org/kMSatGCVL4F5/RWBQpUnJqTPb)
- Ajouter dans les liens à droite le dépôt github ?
- Retirer dans les liens les liens partagés
- typo : 
```
- Cette version apportent des correctifs concernant  
+ Cette version apporte des correctifs concernant :
...
- Nous avons fait évolué
+ Nous avons fait évoluer

```

**Comment by Starsheep08** [comment]
Héhé pas mal !

- Pour ma part la font Roboto ne veut pas se charger. Du coup ça fait ramer le chargement.
- Il manque une favicon. ;)
- Il manque un titre pour avoir quelque chose de plus sexy que "hhtps://blogotext.org" dans l'onglet. :p 
- Les listes à puces sont trop condensées je trouve. Ça fait comme des blocs au milieu du vide.
- Ça manque d'icônes pour rajouter du sexy à la page. :)

Mais c'est déjà un bon début.

**Comment by remrem** [comment]
Merci !
Typo corrigé
je vois pour le reste ASAP ;)

Et j'ai trouvé un petit bug dans l'addon lazyload, je pousse un fix ;)

**Comment by remrem** [comment]
Petite checklist
- [x] Les liens en en-tête sont collés, c'est dommage.
- [ ] Ajouter dans les liens à droite le dépôt github ?
- [x] Retirer dans les liens les liens partagés
- [ ] font Roboto ne veut pas se charger
- [ ] Il manque une favicon. _Des idées ?_
- [x] manque un titre (au prochain refresh par le cron)
- [x] listes à puces sont trop condensées

**Comment by remrem** [comment]
Petite question, BlogoText a eu un logo à une époque ? Si oui, quelqu'un a une source / url / archive ?
@Starsheep08 , tu utilises quel navigateur ? Je n'arrive pas à reproduire le problème :/

**Comment by Starsheep08** [comment]
@remrem J'utilise Firefox mais tout roule maintenant. Un serveur surchargé la première fois que je suis venu peut-être ?

**Comment by remrem** [comment]
@Starsheep08 , possible... (mutu ovh performance 1)

**Comment by remrem** [comment]
Pour info, j'attends de régler les 2-3 points qui restent (et 2-3 autres points) avant de lancer le site officiellement.

**Comment by BoboTiG** [comment]
Nope, pas de logo officiel ; enfin pas encore ? :)

**Comment by remrem** [comment]
Je sens l'âme d'un graphiste en toi @BoboTiG :D

**Comment by remrem** [comment]
[Disponibilité de la release 3.7.3](https://blogotext.org/blog/?d=2017/04/28/19/40/00-blogotext-version-373-disponible).

**Comment by remrem** [comment]
J'ai (encore) mer## avec git, un grand merci @vtedesco pour avoir rattraper le coup ;)

**Comment by remrem** [comment]
Concernant le logo, à part mettre un "BT" dans un carré ou un rond, je sèche ... J'ai bien envie de tenter de pousser le bébé auprès d'un communauté de graphistes et voir ce qu'il en ressort, si personne n'a d'objection ...

**Comment by Starsheep08** [comment]
Si vous voulez je peux tenter un truc. Mais après je ne sais pas si ça va vous plaire. ;)

**Comment by remrem** [comment]
Tu peux toujours proposer ;)

**Comment by B4rb3rouss** [comment]
@Starsheep08 pour avoir vu tes logos pour mangrove entre autres, je ne suis pas du tout inquiet  !

**Comment by Starsheep08** [comment]
![blogotext_logo](https://cloud.githubusercontent.com/assets/8115767/25992092/cf6fbb94-3705-11e7-91bc-84f2059feff1.png)

Un truc dans le style ? Pour le moment c'est juste un concept, ça demande encore du travail.

**Comment by Starsheep08** [comment]
![blogotext_logo](https://cloud.githubusercontent.com/assets/8115767/25992515/06e59eee-3707-11e7-92af-ff1b2d0bdb6a.png)
Un poil mieux. Et on voit mieux où je veux en venir

**Comment by remrem** [comment]
Je tente un truc sur ton 1er ;)
ça va tourner au concours ce truc ... :D

**Comment by remrem** [comment]
les rectangles gris ne sont là que pour délimiter le contour ;)
![](https://framapic.org/x9nyEGBONArP/efAAKz9qG1T9)

**Comment by Starsheep08** [comment]
Ah c'est intéressant avec le bleu. Mais tu n'aspas vu ce que j'essayais de faire... ;) Regarde en détail mon logo, tu devrais y voir... Une plume !

Blog > écriture > plume. Et à partir de là j'essayais de faire un B et T stylisés. :)

**Comment by B4rb3rouss** [comment]
> tu devrais y voir... Une plume ! 

Ah purée c'était ça !
Je voyais un décolleté moi, du coup j'aimais bien... XD

**Comment by Starsheep08** [comment]
Un décolleté ? oO

Ah oui vu de dessus...

**Comment by remrem** [comment]
@Starsheep08 , je dois être vraiment mauvais, je ne la vois pas oO
et la plume, même si c'est une très bonne idée, il y a déjà un autre cms (français, à base d'xml) qui l'utilise, je ne suis pas trop chaud du coup :/
ton premier logo, j'y ai vu la moitié du symbole d'un personnage, du coup, j'étais parti là dessus ...

**Comment by Starsheep08** [comment]
C'est parce que ce n'est pas une plume d'oiseau mais une plume de stylo à plume. ;) Donc ce n'est pas pareil que pluxml. ;)

Mais je vais améliorer ça pour qu'elle ressorte.

**Comment by Starsheep08** [comment]
![blogotext_logo](https://cloud.githubusercontent.com/assets/8115767/26004934/bf02c36e-3737-11e7-8bea-9a625f886289.png)

C'est plus clair là ?

**Comment by remrem** [comment]
Ah oui :) effectivement, il y a du potentiel :D

**Comment by remrem** [comment]
@Starsheep08 , je me suis permis, d'après ta précédente proposition, de pousser un peu plus loin
[img](https://framapic.org/iUWqTcIwBpnM/ldZR8XR6DhRt.png)

**Comment by B4rb3rouss** [comment]
Alors les graphistes, vous en êtes où ?
Perso, j'aime mieux la dernière proposition de @Starsheep08 . On voit bien la plume de stylo. Au pire, ajouter quelques taches d'encre en bas pour renforcer cet effet ?

**Comment by remrem** [comment]
Je vais mettre un sondage avec les différentes propositions ... A la rentrée ?    
Une idée de plateforme ? framadate ?

**Comment by B4rb3rouss** [comment]
Ou bien
https://framaforms.org/

La rentrée ? Ou avant ^^

**Comment by B4rb3rouss** [comment]
Salut !
Je voulais savoir où on en est pour la prochaine version, car apparemment @remrem a bien avancé de son côté. Que reste-t-il à faire? Comment aider? (j'aimais bien le tag "Any help welcome" ;) )

**Comment by remrem** [comment]
Il faut que je passe un coup de polish sur mon code avant de le pousser, il restera du taff dessus, mais pas mal de choses sont en place. Si tu veux donner un coup de main, et que tu es au chaud pour faire du "à côté" (non relatif au code) il y a le dossier "logo" à faire avancer ;)

**Comment by Starsheep08** [comment]
Salut !

Pour le logo, je ne sais pas quoi proposer de plus que ce que j'ai proposé en dernier lieu. ;) Si vous avez des idées je veux bien essayer de retravailler dessus, mais là je sèche. ;)

**Comment by Starsheep08** [comment]
Ou avec du texte comme proposé par remrem ?

![blogotext_logo](https://user-images.githubusercontent.com/8115767/29772835-bd3891fe-8bfa-11e7-9062-252264cd26e9.png)

**Comment by B4rb3rouss** [comment]
Merci pour les précisions.
J'aime beaucoup le logo de @Starsheep08 . Le premier comme "favicon", le second à mettre en grand sur la page d'accueil.
D'ailleurs, tu as les sources? (un .svg?) je tenterai bien d'ajouter une tache d'encre en bas de la plume, bien que le graphisme et moi ça fasse 2...

**Comment by Starsheep08** [comment]
Voilà le svg mais il est dégueulasse. :D 

J'exporte en png, puis je passe sous gimp pour passer le blanc en transparence et redimensionner. Pas eu le temps de faire un beau svg, désolé. ;)

[blogotext_logo.zip](https://github.com/BlogoText/blogotext/files/1256761/blogotext_logo.zip)

**Comment by B4rb3rouss** [comment]
Merci, je vais faire de mon mieux ;)

**Comment by B4rb3rouss** [comment]
Retour :)
J'ai repris le travil de @Starsheep08 et j'ai tout vectorisé. Plus de carrés blanc pour tout cacher donc ;)
voici donc quelques variations : 

![blogotext_logo_sans_txt](https://user-images.githubusercontent.com/9028850/29884864-106fc96c-8db5-11e7-8e2b-b02216508488.png)
![blogotext_logo_sans_txt_2](https://user-images.githubusercontent.com/9028850/29884865-107477b4-8db5-11e7-885f-47d2cf8135b5.png)
![blogotext_logo_sans_txt_encadre](https://user-images.githubusercontent.com/9028850/29884866-10774494-8db5-11e7-8732-2d7205b42143.png)
![blogotext_logo_txt](https://user-images.githubusercontent.com/9028850/29885019-8438c47a-8db5-11e7-95cf-3ad72285131e.png)


[blogotext-logo.zip](https://github.com/BlogoText/blogotext/files/1264427/blogotext-logo.zip)

Pas sûr que ça soit beaucoup mieux, mais peut-être cela vous inspirera ou vous donnera des fichiers à modifier.

**Comment by remrem** [comment]
Hum ... Le 1er et dernier ... [Il n'y a que moi ou ?](https://framapic.org/Xr474X8HsuSP/5fiRQxObVBST)

**Comment by BoboTiG** [comment]
Le dernier pour moi.

**Comment by B4rb3rouss** [comment]
@remrem alors là, je ne m'y attendais pas ^^
C'était pour renforcer l'effet "plume". On peut faire un mélange avec les 2 autres propositions pour réaliser le "T". Peut-être @Starsheep08, plus habitué que moi à inkscape, aura d'autre suggestions ?

**Comment by Starsheep08** [comment]
Entre le B représentant un décolleté vu de haut et la plume représentant des hanches, on commence à être pas trop mal. :D 

Sinon je préfère ce style de ligne que les toutes droites que j'avais proposé. Le seul truc est que l'on commence à vraiment avoir du mal à voir le B et le T. Du coup sur le dernier logo je lis "logo ext". Je vais essayé d'incrémenter encore là dessus. Et merci pour les beaux svg. \o/

**Comment by Starsheep08** [comment]
Allez nouvelle itération. C'est mieux ou c'est pire ?
![blogotext_logo](https://user-images.githubusercontent.com/8115767/29911092-e2d48498-8e2c-11e7-94ec-76e5927730f1.png)

**Comment by B4rb3rouss** [comment]
Je préfère, surtout le "T".
Pour le "B", je tenterai de n'en faire qu'un trait (comme s'il avait été tracé à la plume), sans les séparations pour voir.

**Comment by Starsheep08** [comment]
De ce style ?
![blogotext_logo](https://user-images.githubusercontent.com/8115767/29913883-bda8eba0-8e36-11e7-8595-54ae6c1c683f.png)

**Comment by Starsheep08** [comment]
Peut-être un peu plus équilibré au niveau des épaisseurs ?
![blogotext_logo](https://user-images.githubusercontent.com/8115767/29916050-e6c0baf2-8e3d-11e7-8663-29d58ee28578.png)

**Comment by B4rb3rouss** [comment]
Ah ouais, j'aime bien!Voir si on laisse le gris/transparent à droite ?
Vous en pensez quoi @BoboTiG  et @remrem ?

**Comment by remrem** [comment]
un petit vote en ligne, histoire de ratisser large sur les avis ... non ?

**Comment by B4rb3rouss** [comment]
Là : https://framaforms.org/nouveau-logo-pour-blogotext-1504210334
?

Je vous laisse donner votre accord avant de publier le lien ci et là :)

**Comment by remrem** [comment]
Il manque des logos, le mien, histoire de varier un peu ...
![mon mien](https://camo.githubusercontent.com/3b549a408c492d748ad1eeef7f6c8ce073f5b9c3/68747470733a2f2f6672616d617069632e6f72672f78396e794547424f4e4172502f656641414b7a397147315439)

**Comment by remrem** [comment]
Et si tu pouvez ajouter une option "aucun ne me convaincs" ou un dans le genre, je ne suis pas trop fan du choix "du moins pire" ;)

**Comment by B4rb3rouss** [comment]
Désolé, je croyais avoir tout mis. :s
Voilà ce que ça donne : https://framaforms.org/nouveau-logo-pour-blogotext-1504210334

**Comment by remrem** [comment]
Np.
ça me paraît pas, je pense que l'on peux lancer, non ?

**Comment by B4rb3rouss** [comment]
Peut-être suis-je seul à la voir comme je suis le créateur. Je vois pour rendre les résultats public.

**Comment by B4rb3rouss** [comment]
Hum... C'est pas possible à priori. si tu crées un compte, peut-être peux-tu voir : https://framaforms.org/nouveau-logo-pour-blogotext-1504210334/webform-results

**Comment by remrem** [comment]
Accès refusé :/ Dommage ...

**Comment by B4rb3rouss** [comment]
Dommage oui :/
Je publierai bien sûr les résultats. On publie le formulaire ou c'est bloquant?

**Comment by B4rb3rouss** [comment]
J'ai trouvé!!!! C'était une option bien cachée.

**Comment by B4rb3rouss** [comment]
Les résultats sont disponibles ici : https://framaforms.org/nouveau-logo-pour-blogotext-1504210334/public-results

**Comment by Starsheep08** [comment]
Ben je n'ai que ton choix @B4rb3rouss mais les autres sont cachés... :/

**Comment by B4rb3rouss** [comment]
Peut être suis-je le seul à avoir voté pour l'instant?

**Comment by Starsheep08** [comment]
Ben non j'ai voté mais ça n'apparaît pas.

**Comment by remrem** [comment]
De mon côté ils doivent être entre 4 et 8 à avoir voté ... @B4rb3rouss à casser framaform :rofl:

**Comment by B4rb3rouss** [comment]
C'est très étrange... Peut-être une obscure histoire de cache.
Je vois tous les résultats dans la partie réservée à celui qui a créé le formulaire. Je les publierai bien sûr.
Sinon, on peut utiliser un autre système que framaform. 
On fait quoi, on publie le lien quand même ?

**Comment by remrem** [comment]
Pour ma part, je ne vois que ça ![](https://framapic.org/wAENVzWizzkl/Np9DK2tPqlms)

Si tu as tous les résultats, (il doit y en avoir plus que sur la capture d'écran), on laisse tel quel et tu publieras les résultats, quitte à faire une capture d'écran histoire de ne pas se prendre la tête et de garder ça "open"... non ?

**Comment by B4rb3rouss** [comment]
J'ai la même chose @remrem, il n'y en a pas plus.
Et oui, on rajoutera une capture d'écran s'il y a une différence mais ce n'est pas le cas pour l'instant.

Tu peux donc publier le formulaire au grand public alors :)

**Comment by remrem** [comment]
Hum ... Si tu as la même chose, c'est qu'il manque +- votes ... (vu que `Numéro` commence à `#10` ...) et que j'ai demandé à quelques amis de donner leur avis ... tu n'as pas un récapitulatif avec le nombre de voix par logo ?

**Comment by remrem** [comment]
On peux essayer avec framadate https://framadate.org/pcMbn3FZFzXBq8LO

**Comment by B4rb3rouss** [comment]
Attends, j'avais remis le formulaire à zéro comme j'ai fait plusieurs tests voir si les résultats apparaissaient. Donc si leurs votent n'apparaissent plus c'est "normal".

framadate, je croyais que c'était que pour des dates. Mais en fait non donc c'est mieux! On garde ton lien !

**Comment by remrem** [comment]
Oki, je n'avais pas compris que tu avais fait un reset des votes ...
Bon, si ça te va pour framadate ... ;)

**Comment by B4rb3rouss** [comment]
Tout ça pour ça, je vous jure. Framaforms n'est pas aussi pratique que je croyais.

**Comment by B4rb3rouss** [comment]
On peut filer le lien sur les réseaux ?

**Comment by remrem** [comment]
lol
yep, feu !

**Comment by B4rb3rouss** [comment]
Go !

**Comment by remrem** [comment]
Vu la tournure que prend le sondage, je pense que l'on peux déjà faire un premier bilan : 
1. Je ne m'attendais pas autant de votes, ça c'est cool ;)
2. J'espérais que l'une des propositions se démarque, et en l’occurrence, on en a deux aux coudes à coudes.
3. Il y a pas mal de votes exprimant aucune préférence.
4. Pas beaucoup de commentaires développant ce qui ne va pas, à contrario les quelques commentaires expriment un point qui n'a pas été développé ici, les déclinaisons en différents formats du logo (au moins pour une version miniature genre 40x40px pour la topbar ou autre ...)
5. Je pense que la participation va aller en déclinant au fil du temps, pas besoin de faire traîner en longueur.

Je propose donc, que l'on prenne les 2 logos qui se démarquent, on les peaufines un peu, on les déclinent en petit format et on choisit en "interne", sur cette issue ou une autre celui qu'on adopte, au moins on sera sûr que ça conviendra un maximum.
Qu'en pensez-vous ?

**Comment by Starsheep08** [comment]
Ça me va moi. Ça a au moins permis de dégager le fait que le logo doit présenter du texte. Sinon je suis prêt à décliner le logo en plusieurs tailles.

Et je réfléchissais à comment on pourrait utiliser les deux mais je sèche.

**Comment by remrem** [comment]
Yep, il y avait du bon, avec différents styles, maintenant que l'on y voit plus clair, on peux faire le focus.
Je ne pense pas qu'il faut se prendre la tête à essayer de "fusionner" les deux, on les fait au propre et on s'en tient à ça.
ça sent bon le lancement de la 3.8 + le site officiel + le logo d'ici la fin d'année ;)

**Comment by remrem** [comment]
J'ai refait (un peu à l'arrache) mon logo avec différentes déclinaisons, [tout est dans le zip](https://framadrop.org/r/mGQW6X4vf6#vQCMvEdeHKMY7OB65aUVaxrwaSXiv3dqPSmpXOH85jw=).

@Starsheep08 En attente du tiens ;)

![](https://framapic.org/waiNamvzhs4q/e8TQh5IYsugP)
![](https://framapic.org/iZ67rkR7TT0c/88NNjznKTmUy)
![](https://framapic.org/d0iqlJMn0COQ/OfMUxhxHgxlE)
(celui là sert pour les favicons...)

**Comment by Starsheep08** [comment]
Ah pas mal ce que tu as fait là @remrem ! Je retouche le logo "plume" ce weekend. :)

**Comment by B4rb3rouss** [comment]
>  ça sent bon le lancement de la 3.8 + le site officiel + le logo d'ici la fin d'année ;)

Rien de spécial à dire, mis à part que je suis hyper content

**Comment by Starsheep08** [comment]
Allez zou. J'ai pas modifié grand chose au logo en lui-même mais dans le zip il y a des svg tous propres cette fois.

Et j'ai rajouté des fichiers monochromes et il y a une version sans texte.

Enfin je vous laisse découvrir ça.

[blogotext.zip](https://github.com/BlogoText/blogotext/files/1289936/blogotext.zip)

![logo](https://user-images.githubusercontent.com/8115767/30242088-34f82e9a-9590-11e7-8658-338b8cd55c7a.png)
![logo_mono](https://user-images.githubusercontent.com/8115767/30242086-34f01caa-9590-11e7-96b1-b1dd94a0d39a.png)
![logo_text](https://user-images.githubusercontent.com/8115767/30242091-3b86b2c2-9590-11e7-95ff-01880986b89b.png)
![logo_text_mono](https://user-images.githubusercontent.com/8115767/30242087-34f4d86c-9590-11e7-8a7f-fddee06220a1.png)

**Comment by remrem** [comment]
On partirai sur la version avec le texte (comme pour le sondage ?)
Il y a quelques petits problèmes, le font n'est pas attaché, il faudrait soit l'incorporé soit vectorisé les textes pour les svg, et tu arriverais à faire quelques choses pour les tout petits formats ? Grossir les traits ou autres ? pas très "lisible". Je peux paraître un poil chiant, mais j'essaye de voir pour l'intégration ... ;)

**Comment by Starsheep08** [comment]
La version sans texte étant uniquement destinée au favicon, je vais l'épaissir oui. Et c'est un problème que la font ne soit pas incorporée... Je vais vectorisé tout ça et même tenter d'améliorer la police. :)

**Comment by remrem** [comment]
oki, merci ;)

**Comment by remrem** [comment]
[Release 3.7.5 is out!](https://github.com/BlogoText/blogotext/releases/tag/3.7.5)

**Comment by B4rb3rouss** [comment]
✌️ Yay :)

**Comment by remrem** [comment]
Pour information, j'ai verrouillé le sondage, plus de votes depuis quelques temps (...) les résultats demeurent [visible publiquement](https://framadate.org/pcMbn3FZFzXBq8LO).

La petite note que j'ai ajouté : 

> **UPD**
Un grand merci à tous les participants de ce sondage, vos avis et commentaires nous ont permis d'y voir un plus clair dans le choix du nouveau logo pour BlogoText. Nous avons retenu les deux logos qui sont en tête et au coude-à-coude, nous allons les retravailler en prenant en compte vos commentaires et allons choisir celui qui conviendra le plus aux besoins.
Merci ! RemRem.

**Comment by Starsheep08** [comment]
Merci @remrem. Ça m'a fait penser que je n'avais toujours rien envoyé... Alors je me rattrape. 

Voilà encore une nouvelle itération avec prise en compte des remarques de @remrem.

![logo](https://user-images.githubusercontent.com/8115767/30495349-00e22690-9a4c-11e7-8227-44fd2d9d1c9e.png)
![logo_mono](https://user-images.githubusercontent.com/8115767/30495352-03684c32-9a4c-11e7-957b-37b5d41c3ecd.png)
![favicon-32](https://user-images.githubusercontent.com/8115767/30495369-0c0dc54c-9a4c-11e7-9d22-b4e64ae5a564.png)

[blogotext.zip](https://github.com/BlogoText/blogotext/files/1307144/blogotext.zip)

**Comment by B4rb3rouss** [comment]
Oh, très chouette avec la nouvelle police.

**Comment by B4rb3rouss** [comment]
Du coup ça donne quoi pour la 3.6 ? Besoin d'un coup de main sur quelque chose?

**Comment by remrem** [comment]
Yop, débordé depuis 15 jours, pas eu trop le temps de faire le cleanup :/ je fais le cleanup et je revois la sécurité ce week end, je pousse sur la branche dev fin de W.E.

**Comment by remrem** [comment]
[3.7.6 is out](https://github.com/BlogoText/blogotext/releases/tag/3.7.6), elle corrige une faille XSS, je ne peux que recommander de mettre à jour ...
P.S. Il faut vraiment que l'on voit pour cette histoire de logo et pour mettre le site en place ... Je pousse demain une modif de ma proposition de logo et j'aimerai qu'on se décide rapidement à ce propos. Et mes travaux sur la 3.7.6-dev arrivent demain ;)

**Comment by B4rb3rouss** [comment]
Super tout ça, merci beaucoup :)

**Comment by remrem** [comment]
![](https://framapic.org/hk6IZ2S432BT/vjlmeBROkUik)
![](https://framapic.org/4q5toByN0GbS/Cv6xspvr2RsD)
![](https://framapic.org/tc7XmqFXU0cP/6P2SceOjy5Hl)
[Source](https://framadrop.org/r/I9TSFn_KK2#2OhNDYhJLe7BkM02SqzFl8HrnwNj9KhNp3Xoe3eQAZk=)
Voilà, version corrigée (font & licence) juste cleanup et version compressée à prévoir.
Pour info, la font utilisée est [cabin](https://fonts.google.com/specimen/Cabin)

Alors, on part sur lequel ? Celui de ce post ou celui de @Starsheep08 [juste au dessus](#issuecomment-329846890) ?     

Ajoutez votre "réaction" (l'icône smiley en haut à gauche de commentaire) pour voter.
:tada: pour le mien
:heart: pour celui de @Starsheep08 

@BoboTiG @B4rb3rouss @Starsheep08 @extragornax ...
Thanks.

P.S. après la cloture du vote, je ferme cette issue, elle commence à être vraiment trop longue... :rofl:

**Comment by B4rb3rouss** [comment]
a voté ;)

**Comment by B4rb3rouss** [comment]
On a une égalité là, il faut trancher les autres ;)

**Comment by remrem** [comment]
Je compte sur @BoboTiG pour trancher... :D

**Comment by Starsheep08** [comment]
On ne s'en sortira jamais... ;)

**Comment by BoboTiG** [comment]
A voté :)

**Comment by remrem** [comment]
Je pense que nous avons notre logo ;)
Merci pour les créations et pour la participation.

Je ferme cette issue, elle est vraiment trop longue.
Au besoin, on en crée une autre.
