### ISSUE TITLE
Installation option pour peupler le blog

### ISSUE THREAD

**Issue by remrem** [BlogoText/blogotext#246]
Je viens de me farcir 5 installations de BlogoText, non pas que ça soit pénible en soi, mais le fait de devoir nettoyer les articles, coms, liens par défaut, et un poil lourd, on ne mettrai pas une petite option dans le processus d'installation pour désactiver ça ?

**Comment by B4rb3rouss** [comment]
C'est parce que tu as fait des installs à la pelle que c'est pénible. Mais sinon, ça reste chiant oui :)
