### ISSUE TITLE
Lecteur de flux RSS cassé

### ISSUE THREAD

**Issue by Starsheep08** [BlogoText/blogotext#247]
Salut !

Depuis la mise à jour vers BlogoText 3.7 mon lecteur de flux RSS n'affiche plus rien, n'actualise plus rien et ne supprime plus rien.

Ne serait-ce pas ma version de Libxml (2.7.6) qui ne serait plus compatible ?

**Comment by remrem** [comment]
Je ne sais pas, pas assez d'infos.

Ce que tu peux tester : 
1. lancer le cron manuellement depuis ton navigateur, L'url se trouve dans l'administration > Préférences > "Ligne "crontab" pour MÀJ auto des flux"
2. si tu lances les manipulations depuis depuis l'interface d'administration, ouvrir les outils de développeurs de ton navigateur et regarder dans la console pour voir si il y n'y pas de message d'erreur
3. les logs apaches/PHP

Pour l'instant, je ne peux pas faire plus ... :/

**Comment by Starsheep08** [comment]
Alors j'ai un peu plus d'infos.
L 428 du fichier admin/feed.php : 
`            Rss = rss_entries.list;`
la console me dit : 
`ReferenceError: rss_entries is not defined`

**Comment by Starsheep08** [comment]
Bizarrement, tout refonctionne à partir du moment où j'ai supprimé les entrées périmées dans la liste des flux suivis...

**Comment by remrem** [comment]
Ok oO ... va quand falloir se pencher là dessus ...

**Comment by remrem** [comment]
Je n'arrive pas à reproduire ce bug :/ Si en nettoyant les flux ça fixe le problème, c'est toujours une solution en attendant de trouver mieux ...

**Comment by Starsheep08** [comment]
C'était peut-être l'association de plusieurs facteurs : 

- des liens morts dans la liste des flux,
- la màj vers 3.7,
- une BDD de nouveaux articles non vide.

Maintenant que le lecteur est reparti, je n'arrive pas à le refaire buguer...

**Comment by remrem** [comment]
Peut-être ...
On va laisser l'issue ouverte au cas où ...

**Comment by Starsheep08** [comment]
Faut voir le temps que tout le monde fasse la màj, et si il n'y a pas d'autres plaintes on pourra fermer oui. :)

**Comment by remrem** [comment]
La version 3.7.3 doit corriger le tir, merci d'avoir soulever le problème ;)
