### ISSUE TITLE
Problème à l'installation de BT

### ISSUE THREAD

**Issue by lanargeek** [BlogoText/blogotext#267]
Bonjour,
Impossible de finir l'installation de BT car il me crache un joli message d'erreur au pif:
"Fatal error: Uncaught Error: Call to undefined function idn_to_ascii() in /home/maxime/site/www/blog1/inc/boot.php:177 Stack trace: #0 /home/maxime/site/www/blog1/inc/boot.php(254): secure_host_to_path('http://192.168....') #1 /home/maxime/site/www/blog1/admin/inc/boot.php(17): require_once('/home/maxime/si...') #2 /home/maxime/site/www/blog1/admin/install.php(19): require_once('/home/maxime/si...') #3 {main} thrown in /home/maxime/site/www/blog1/inc/boot.php on line 177"
Peut être une mauvaise config sur mon hébergement perso mais j'ai tenté la màj depuis BT 3.4.7 en suivant les étapes indiquées puis une install clean.
Merci d'avance :)

**Comment by B4rb3rouss** [comment]
Aaah, je réalise seulement, tu as besoin d'avoir l'extension "intl" d'installé pour PHP.
C'est mis dans le README, mais pas dit dans les notes de mise à jour, et c'est souvent livré avec PHP...

**Comment by lanargeek** [comment]
Oh là là...comme quoi lire le Readme devrait être une obligation:)
Merci beaucoup, je m'en doutais que cela venait de ma configuration du bousin

**Comment by remrem** [comment]
@lanargeek , du coup, ça va le faire ou il te faut une autre solution ?

**Comment by lanargeek** [comment]
@remrem tout est bon :) problème résolu !

**Comment by remrem** [comment]
Bonjour,
La release 3.7.2 règle le problème de l'extension intl par l'ajout de tests et de messages d'erreur à l'installation et à la mise à jour de BlogoText. Si le problème est réglé et que votre BlogoText 3.7.1 est fonctionnel, pas besoin de passer à la version 3.7.2 ;)
Merci d'avoir soulevé le problème ;)
