### ISSUE TITLE
Fatal Error pendant la mise à jour

### ISSUE THREAD

**Issue by remadounet** [BlogoText/blogotext#268]
J'ai suivi le process indiqué
Faire un backup (a la barbare)
`cp -r Blogotext/ Blogotext-Backup/`
supprimer les dossiers
`rm -Rf Blogotext/addons/ Blogotext/myAdmin/ Blogotext/cache/ Blogotext/inc/`
récupérer la version 3.7.0
`wget https://github.com/BlogoText/blogotext/archive/3.7.0.zip`
`unzip 3.7.0.zip`
écraser les fichiers
`cd blogotext-3.7.0/`
`cp -Rf * ./../Blogotext`
Je met des bonnes permissions, puis je vais sur la page admin, la première page fonctionne bien, mais quand il y a le lien pour changer de mot de passe, je clique dessus et j'ai cette erreur:

> Fatal error: Call to undefined function idn_to_ascii() in .../Blogotext/inc/boot.php on line 177

Que faire?

**Comment by B4rb3rouss** [comment]
Afin de résoudre ce souci, vérifiez que la bibliothèque PHP "intl" est bien installée et active.
La 3.7.1 est disponible pour info.

**Comment by remrem** [comment]
ça sent la 3.7.2 avec une solution de repli au cas où intl n'est pas dispo ... ;)
@remadounet , tu peux installer intl ou c'est bloquant pour toi ?

**Comment by remadounet** [comment]
@remrem je viens de l'installer, et tout semble nickel :)
C'est sur mon raspberry pi perso, mais je m'y connais pas trop dans tout ce qui est web-related (style librairies php)

**Comment by remadounet** [comment]
@B4rb3rouss @remrem J'ai pu installer la bibliothèque intl, Blogotext est pour le moment sur un raspberry pi personnel. Mais j'ai peu de connaissances dans tout ce qui est web-based.
Tout à l'air de fonctionner après ça, sauf la partie la plus importante pour moi: le flux RSS:
J'ai l'impression d'avoir plus ou moins le même problème que #247 : La liste des flux est correcte et m'affiche des posts non lus, mais je n'ai plus de résultats, et je n'ai plus le nombre d'éléments en haut à droite, simplement "éléments".
La console me dit:

> SyntaxError: expected expression, got '}' feed.php:6:772
> ReferenceError: rss_entries is not defined feed.php:27:13

**Comment by remrem** [comment]
Ok, je crée une autre issue pour le problème des RSS

**Comment by remrem** [comment]
Bonjour,
La release 3.7.2 règle le problème de l'extension intl par l'ajout de tests et de messages d'erreur à l'installation et à la mise à jour de BlogoText. Si le problème est réglé et que votre BlogoText 3.7.1 est fonctionnel, pas besoin de passer à la version 3.7.2 ;)
Merci d'avoir soulevé le problème ;)

Pour le problème de flux, j'ai créé une issue, cf. #269 . Je clôture cette issue ;)

**Comment by remadounet** [comment]
Il semble que cliquer sur le bouton "Recharger" a suffi à tout régler. Je pense que c'est un problème lorsqu'il y a des flux non lus avant la mise à jour, qui ne sont pas au bon format après la mise à jour.
