### ISSUE TITLE
Installation page perso free.fr

### ISSUE THREAD

**Issue by yoalor** [BlogoText/blogotext#274]
Bonjour, lors de l'installation de blogotext 3.7.2 sur les pages perso de free.fr, j'obtiens le message d'erreur suivant : BlogoText requires that the PHP intl extension be installed and activated. Installation aborded.
J'ai mis dans le fichier .htaccess la version de php 5.6, sinon j'ai une erreur directement.
Cordialement.

**Comment by remrem** [comment]
Bonjour,

Je ne connais pas suffisamment le service d'hébergement de free, mais à en croire [l'assistance](http://www.free.fr/assistance/943.html), ça à l'air d'être assez ... restrictif ...

Je n'ai pas trop compris, il faut forcer PHP 5.6 via un .htaccess pour pouvoir procéder à l'installation, ou ça bloque toujours ?

Si ça bloque, je vais pousser une nouvelle révision pour se passer de l'extension intl.

**Comment by yoalor** [comment]
Oui, si je ne force pas le php en 5.6, l'installation est impossible.
Avec le php en 5.6, je peux procéder à l'installation. J'ai mon erreur après avoir saisie un utilisateur et un mot de passe.
Effectivement, free est très restrictif...

**Comment by remrem** [comment]
Ok, je vois pour pousser un fix, peut-être dans la journée.

**Comment by yoalor** [comment]
Wahou, super réactivité! Pas de problème pour tester dès que c'est prêt. Mais ne t'inquiètes pas, rien ne presse.

**Comment by remrem** [comment]
Un peu à la bourre, mais si tu veux tester la branche [compat-free](https://github.com/BlogoText/blogotext/tree/compat-free)
ou directement télécharger le [zip](https://github.com/BlogoText/blogotext/archive/compat-free.zip)

**Comment by yoalor** [comment]
Alors, on progresse!
J'ai pu choisir le SDGB à utiliser. J'ai choisi MySQL et renseigner les différents éléments mais quand je valide, j'ai un nouveau message d'erreur : 
Fatal error: Call to a member function setAttribute() on null in install.php on line 431
Cordialement.

**Comment by remrem** [comment]
Ok, bon ...
tu peux essayer avec les modifications de la branche [compat-free](https://github.com/BlogoText/blogotext/tree/compat-free)
ou directement télécharger le [zip](https://github.com/BlogoText/blogotext/archive/compat-free.zip) ?
J'ai modifié le test de connexion à la base de données, si ça plante, ça devrait être un peu plus bavard ;)

**Comment by yoalor** [comment]
J'ai tester et eu le même problème. J'ai fait un peu de recherche et en faite, j'ai du mal renseigner les paramètres SQL qui sont spécifiques à free...
Par contre, j'ai eu un autre problème. Il maque une colonne dans la table article. A savoir, la colonne 'bt_tags'. Je l'ai créé avec les mêmes paramètres que la table 'bt_notes'.
J'ai donc réussi à me connecter en utilisateur pour avoir un rendu du blog et aussi à créer un article.
Je t'ai fait bosser pour rien sur la deuxième version. Désolé...

**Comment by yoalor** [comment]
Et sur le RSS, il manque, la colonne 'bt_bookmarked' dans la table RSS.
Après ajout de la colonne, plus d'erreur sur le RSS.
A+

**Comment by remrem** [comment]
Pas de soucis, je vais quand même regarder cette histoire de colonne manquante ... Je cloture, en cas de problème n'hésite pas à ouvrir une nouvelle issue ;)

**Comment by yoalor** [comment]
OK, merci pour ton support et ton aide.
Super réactivité!
A+
