### ISSUE TITLE
Problème php dans les liens

### ISSUE THREAD

**Issue by gglt** [BlogoText/blogotext#280]
Bonjour,

En v3.7.x, sous le bandeau menu, lorsque je veux consulter mes liens, j'ai ce message : 
Notice : Use of undefined constant ARRAY_FILTER_USE_KEY - assumed 'ARRAY_FILTER_USE_KEY' in [caché]/blog/admin/inc/form.php on line 207
Warning : array_filter() expects at most 2 parameters, 3 given in [caché]/blog/admin/inc/form.php on line 207

J'étais en v3.4.7 ==> aucun problème
J'ai suivi les instructions pour passer à la v.3.7.0 puis la v3.7.3 ==> le problème est apparu avec la v3.7.0 et n'a pas disparu avec la v3.7.3
J'ai tenté une "install from scratch" de la v3.7.3 puis j'ai importé mes liens ==> le problème est réapparu

Que faire ?

Cordialement,

**Comment by remrem** [comment]
Salut,
Je jette un coup d'oeil en essayant de reproduire le problème.

**Comment by remrem** [comment]
à tout hasard, tu n'utiliserais pas une version de PHP inférieur à la 5.6 ? Peux-tu préciser la version que tu utilises ?
Il faut que je fasse du code review pour déterminer la version nécessaire de PHP, nous avons (beaucoup) retravaillé le coeur de BT pour la version 3.7 et il se peut que nous aillons cassé involontairement la compatibilité avec PHP 5.X < 5.6 :/
J'essaye de pousser un correctif ce week end.
En tout cas, merci d'avoir reporté le problème :+1:

**Comment by gglt** [comment]
Effectivement, je suis en php 5.5.9. Je suis surpris de ne pas avoir la dernière version puisque mon serveur tourne sur ubuntu avec les maj ausi souvent que je peux.

**Comment by gglt** [comment]
Vérification faite : mon serveur tourne sous Ubuntu 14.04.5 LTS ...
Il y a une nouvelle LTS que je n'ai pas encore pris le temps d'installer. C'est peut-être pour ça que je n'ai pas une version php supérieure. Je vais creuser la piste.

**Comment by remrem** [comment]
Yep, je crois que ubuntu 14.04 ne supporte pas PHP > 5.5, en attendant la prochaine release de blogotext (demain ou lundi), tu peux essayer la branche master, j'ai poussé un [fix rapide](https://github.com/BlogoText/blogotext/commit/c625552d0902fdbaaf9315b85cd1be31771d3cb6)

**Comment by gglt** [comment]
J'ai clos l'autre bug ... Après réflexion, n'étant pas famillier du workflow git, j'ignore si c'est bien a moi de le faire. Je te laisse donc le soin de procéder ici, sauf si tu préfères que je le fasse.

**Comment by remrem** [comment]
Peu importe, du moment que le problème est réglé et que tout est bon ;)
