### ISSUE TITLE
Problème dans les flux

### ISSUE THREAD

**Issue by gglt** [BlogoText/blogotext#281]
Bonjour,

En v3.7.x, les flux fonctionnent bizarrement chez moi. Un clic sur le titre d'un flux me permet de l'ouvrir comme auparavant jusqu'en v.3.4.7. Un second clic sur ce même titre m'ouvre maintenant la page du flux complet avec tous les titres du flux. Auparavant, je tombais sur la page de l'article lui même.

Je fonctionne sur la v3.7.3 en "install from scratch" avec import des flux opml.

Qu'est-ce qui coince ?

Cordialement,

**Comment by remrem** [comment]
Effectivement, il y a bug :/
Nous avons retravaillé l'affichage des flux pour permettre l'affichage des flux par "pages" ce qui permet d'afficher les flux plus rapidement lorsque il y en a beaucoup à afficher, et il s’avère qu'une erreur a été commise dans la modification du template, je pousse un correctif rapidement (durant le W.E. si tout va bien).

Merci d'avoir reporté le problème ;)

**Comment by gglt** [comment]
Super ! Merci :-)

**Comment by remrem** [comment]
Si tu peux tester la [branche master](https://github.com/BlogoText/blogotext/archive/master.zip), cette issue et la #280 devraient être réglées ;)
J'attends que tu confirme pour pousser la nouvelle release.

**Comment by gglt** [comment]
Bravo remrem :-)

C'est du beau travail ! Propre et rapide ... trop rapide même, car tu as certainement dû le faire en bouffant une partie de ton week-end :-(

En tous cas, pour ma part, les 2 bugs sont bel et bien résolus.

Merci encore pour le travail.

**Comment by remrem** [comment]
No problem ;)
