### ISSUE TITLE
Notifications par mail

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#284]
Bon en fait, la notification par mail d'un nouveau commentaire en plaintext n'est pas terrible, certains lecteurs de courriels ne détectent pas l'URL et donc impossible de cliquer...

Une idée pour améliorer ça  et avoir un truc qui marche bien qu'on ait un parseur html ou non en lecture?

**Comment by remrem** [comment]
on peut faire du mixed html/text, le client n'affiche que le HTML si il le gère.
Sinon, autre idée, pour la prochaine release (3.8), je revois un peu la home page de l'administration, il y a peut-être aussi un truc à faire à ce niveau là...

**Comment by B4rb3rouss** [comment]
ok, bon, du boulot alors ^^
Je tente de m'en occuper si j'ai le temps les semaines à venir.

Y a du boulot dans blogotext et du nettoyage à faire je crois, mais ça en vaut la peine.

**Comment by remrem** [comment]
yep, bien que j'ai pas trop le temps de me poser sérieusement dessus, je prépare un PR assez sympa prochainement.
Pour les mail, je pense que l'on peut partir avec du  [PHPmailer](https://github.com/PHPMailer/PHPMailer) pour l'interface pop/smtp et pour faciliter le mix html/text.
Les lib sont à placer dans un dossier `/inc/lib/`. Par contre, j'ai revu l'interface et les fonctions liés aux "settings/paramètres"...

**Comment by B4rb3rouss** [comment]
Ouuuuh, suspense :)

j'ai envoyé une PR avec un truc vraiment tout simple piqué sur le net qui ne fait pas appel à une lib externe. Et ma foi, ça semble bien fonctionner d'après mes quelques tests. À vérifier par des pros ;)

**Comment by remrem** [comment]
ça me paraît pas mal, je vois ça plus en détail cet après-midi.
Par contre pour la lib, avec le support pop/smtp, je pense que l'on n'y pas y échapper ...

**Comment by B4rb3rouss** [comment]
Lors d'un commentaire publié via l'interface d'administration, ça coince, j'ai du oublier un truc : 

```
Notice: Undefined index: mail_subject in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 432

Notice: Undefined index: mail_message1 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 450

Notice: Undefined index: mail_message2 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 450

Notice: Undefined index: mail_message3 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 450

Notice: Undefined index: mail_see in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 451

Notice: Undefined index: mail_link in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 451

Notice: Undefined index: mail_unsub in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 453

Notice: Undefined index: mail_unsuball in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 454

Notice: Undefined index: mail_end in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 456

Notice: Undefined index: mail_regards in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 458

Notice: Undefined index: mail_message1 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 466

Notice: Undefined index: mail_message2 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 466

Notice: Undefined index: mail_message3 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 466

Notice: Undefined index: mail_see in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 467

Notice: Undefined index: mail_link in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 467

Notice: Undefined index: mail_unsub in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 468

Notice: Undefined index: mail_unsuball in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 469

Notice: Undefined index: mail_link in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 470

Notice: Undefined index: mail_regards in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 470

Notice: Undefined index: mail_message1 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 450

Notice: Undefined index: mail_message2 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 450

Notice: Undefined index: mail_message3 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 450

Notice: Undefined index: mail_see in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 451

Notice: Undefined index: mail_link in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 451

Notice: Undefined index: mail_unsub in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 453

Notice: Undefined index: mail_unsuball in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 454

Notice: Undefined index: mail_end in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 456

Notice: Undefined index: mail_regards in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 458

Notice: Undefined index: mail_message1 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 466

Notice: Undefined index: mail_message2 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 466

Notice: Undefined index: mail_message3 in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 466

Notice: Undefined index: mail_see in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 467

Notice: Undefined index: mail_link in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 467

Notice: Undefined index: mail_unsub in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 468

Notice: Undefined index: mail_unsuball in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 469

Notice: Undefined index: mail_link in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 470

Notice: Undefined index: mail_regards in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 470

Warning: Cannot modify header information - headers already sent by (output started at /htdocs/yeuxdelibad.net/Blog/inc/util.php:467) in /htdocs/yeuxdelibad.net/Blog/inc/util.php on line 210
```

Le commentaire est posté quand même, mais bon...

**Comment by remrem** [comment]
Il me semble que c'est relatif aux fichiers langues public/admin...

**Comment by B4rb3rouss** [comment]
On a donc deux fichiers de lanques, un public et un admin, on dirait bien.

C'est logique? Il y a une raison particulière pour la sécurité ?

Sinon, ça me semble plus simple de tout avoir ua même endroit, non ?

**Comment by remrem** [comment]
Oui, on a divisé les fichiers lang en 2 partie, 1 publique et 1 admin, pour plusieurs raisons : 

- ça permet de ne charger que ce qui est nécessaire, pas besoin de charger un tableau php de plus de 500* items, alors que le public n'en utilise que 200*, performance (...) 
- cohérence avec la volonté de séparation public/admin
- ça va permettre de jouer plus facilement sur les fichiers lang des templates (public)

Donc là, pour le coup, et à défaut de mieux, il faut retranscrire dans les 2 fichiers langs ...
A voir si pas moyen de faire mieux pour le coup...
L'avantage, c'est que tu peux "personnaliser" les textes pour souligner que c'est l'admin qui répond ...

* chiffres approximatifs

**Comment by B4rb3rouss** [comment]
J'envoie une PR dans les jours à venir.

**Comment by remrem** [comment]
Ok ;)

**Comment by B4rb3rouss** [comment]
Et voilà, c'est trois fois rien, les messages peuvent bien sûr être modifiés.

**Comment by remrem** [comment]
Mergé ;)

**Comment by B4rb3rouss** [comment]
Merci !
