### ISSUE TITLE
Optimisation base de données

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#286]
Avec SQLite, dans la partie admin, peut-être proposer d'optimiser la base qui enverra un "VACUUM" ?

**Comment by remrem** [comment]
J'y ai pensé aussi ... mais plus dans la partie maintenance.

**Comment by B4rb3rouss** [comment]
ok, donc en fait ça existe déjà : https://github.com/BlogoText/blogotext/blob/dev/admin/maintenance.php#L845

je suis un boulet

**Comment by remrem** [comment]
> je suis un boulet

Pas vraiment, c'est le manque de documentation qui n'aide pas ;)
