### ISSUE TITLE
[links] Partage automatique vers réseaux sociaux

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#297]
Une idée à étudier : lors de l'ajout d'un lien (et/ou d'un article?), il serait intéressant de publier ce lien vers les réseaux sociaux enregistrés dans la partie administration (diaspora, mastodon, twitter...)
Je suppose qu'un plugin serait plus intéressant.
Bref, je laisse l'idée là pour voir les réactions et si ça semble possible.

**Comment by remrem** [comment]
Je pense que ça le relève plus de l'addon (comme pour #223 ).
Je vais mettre en place des hook dans l'administration

**Comment by B4rb3rouss** [comment]
À y réfléchir, il serait peut-être plus judicieux de ne pas intégrer cette idée à blogotext mais en faire un outil indépendant "feed to social".

**Comment by remrem** [comment]
Si c'est pour proposer une solution externe à BT, il doit déjà exister des bouts de code ou solution plus complète pour ce besoin.
Je ne suis pas trop chaud pour me lancer dans un autre dev open source autre que BT en ce moment...

**Comment by B4rb3rouss** [comment]
Après mure réflexion, c'est plus intéressant en externe. Peut-être même sans PHP, je m'y colle un de ces jours.

**Comment by B4rb3rouss** [comment]
Juste pour info, si ça intéresse des contributeurs, j'ai entammé un outil qui implémente cette fonctionnalité ici : https://framagit.org/Thuban/noizy
