### ISSUE TITLE
ServerName and ServerAlias

### ISSUE THREAD

**Issue by ragnar76** [BlogoText/blogotext#301]
Hey,

i have configured my Apache like this:

```
ServerName somedomain.net
ServerAlias www.somedomain.net
```

So, when i call somedomain.net everything is working fine but when i call www.somedomain.net i get this error:

`Your HTTP HOST doesn't match the config of this BlogoText`

how can i avoid this and make my installation make use of both domains?

**Comment by remrem** [comment]
Hi,

yes, 2 solutions : 
1. The best (SEO, sharing ...), you can add a Apache redirection www.somedomain.net -> somedomain.net (or no www to www.)
2. Add a BlogoText VALIAS, english documentation not available, but if you choose this solution, I can write a quick how-to.

(Sorry for my english)

**Comment by ragnar76** [comment]
thanks -> closed
