### ISSUE TITLE
Checkbox for deleting multiple posts at once

### ISSUE THREAD

**Issue by ragnar76** [BlogoText/blogotext#302]
this would be nice to have :)

**Comment by remrem** [comment]
I'm not really sure this is very useful, in normal use, I don't see any case of you need to delete enough articles to add this feature.
This is a feature you will need regularly ?

**Comment by ragnar76** [comment]
to be honest? no but i've tried to import my old wordpress stuff and it was a total mess, i had to delete it all. my solution was to use phpliteadmin to delete the articles but i dont know whats left

**Comment by remrem** [comment]
Ok, I understand better your need, Wordpress import really need some works  #182 ;)
Need help for importing your WP export ?
Can you keep a copy of your Wordpress export ? Could be useful to test import when we will work on it ...

**Comment by ragnar76** [comment]
Right now i'm playing with blogotext (for example, made a bootstrap theme from scratch to understand how it works.
Not perfect, made in about 2 hours [https://chaosadmins.de]) but i will use it later so i can keep the XML File from wordpress

**Comment by remrem** [comment]
Ok, do not hesitate to create an issue if you need help. For information, there are big changes planned in the next versions (addon for the 3.8, template for the 4.0...).

Can we close this issue ? (linked to #182)

**Comment by ragnar76** [comment]
Sure :)
