### ISSUE TITLE
No space in categories

### ISSUE THREAD

**Issue by ragnar76** [BlogoText/blogotext#310]
the categorie tags are sticked together

**Comment by remrem** [comment]
I just think about it, I believe there is no space voluntarily (it was already there when BT changed maintainer). To add space, it must be done by css.

I think the best solution is to leave it in the state (BT side) to not break the templates of the other BT users. We can change this behavior in the next major release.

So, for now, all I can tell you is to add a CSS like : 
```
CSS_path_to_the_parent a
{
 margin-right: X px/em/rem;
}
CSS_path_to_the_parent a:last-child
{
 margin-right: 0;
}
```

**Comment by ragnar76** [comment]
OK, sounds good for me -> Close then

**Comment by remrem** [comment]
Ok, thanks.
