### ISSUE TITLE
C-LX RSS

### ISSUE THREAD

**Issue by Starsheep08** [BlogoText/blogotext#315]
@timovn improved the BlogoText RSS aggregator which results in a performance gain.

Sources : https://github.com/timovn/C-LX-RSS

Would it be possible to replace BT-RSS by C-LX-RSS ?

**Comment by remrem** [comment]
Hi, @BoboTiG ask me the same question some time ago, and this answer is the same, "no, we can't" :/
for 2 major raison : 
* We have do some change on BT, so using C-LX-RSS will require some rewrite of the C-LX-RSS code.
* C-LX-RSS doesn't use a "page" system, I try it an some page are really heavy (more than 2mb), and I don't want an another issue like #145

I know that the "page" change bring some bugs with BT 3.7.X, but you know the hard work behind this change and I hope you will not be disappointed by the next changes coming with the version 3.8.

**Comment by remrem** [comment]
@Starsheep08 I let you close this issue when you have read my answer.

**Comment by Starsheep08** [comment]
Oh sorry, I had already read your explanations in my e-mails but I forgot to reply.

I close the issue in regards of your very compelling arguments. ;)
