### ISSUE TITLE
"Reply" not parsed

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#323]
When clicking on "Reply" to post a comment, it produces this code as example : 

    [b]@[xuenga|#id921d2a][/b]

Since 3.7.6, it is not parsed and appears like this.

**Comment by remrem** [comment]
My bad, I didn't check this when I run the 3.7.6 tests :/
[link|...] and @[user|id] have a similar syntax and [user...] seems to fall into the new [link...] security filter...

**Comment by B4rb3rouss** [comment]
Such things happens, the most important was the security issue, don't worry. ;)
One day, we'll use markdown or txt2tags syntax instead (just kidding).

**Comment by B4rb3rouss** [comment]
Probably the same issue. Now, when you write `<code>hello world</code>` in an article, the `<code>...` is hidden.

**Comment by remrem** [comment]
3.7.6 haven't any modification to any HTML tags or `[code]`
I try
```<code>Test with HTML tag</code>
[code]Test with MarkupCode[/code]
[code]<code>Test with HTML tag inside MarkupCode</code>[/code]```
I try with 3.7.5 and 3.7.6 and it seems that `<code>` is always interpreted as html `<code>` (check the HTML source code of you article, public side).

If you try my example, you must have something like (public side) ;
```
<p><code>(...)</code></p>

<pre><code>(...)</code></pre>

<pre><code>&lt;code&gt;(...)&lt;/code&gt;</code></pre>

```

**Comment by B4rb3rouss** [comment]
My bad, with your code, it works as expected. Hum, I'm confused, I'll have to double check. Sorry for the noise. :/

**Comment by remrem** [comment]
@B4rb3rouss np ;)

**Comment by B4rb3rouss** [comment]
Hi,
I tried this, it seems to work but I'm not sure how to reproduce the previous bug (security issue) it was supposed to fix : 

```
function markup_clean_href($matches)
{
    // var_dump($matches);
    $allowed = array('http://', 'https://', 'ftp://', '#id[\w]+');

    // if not a valid url, return the string
    if (filter_var($matches['2'], FILTER_VALIDATE_URL)
     || preg_match(';^('.join('|', $allowed).');i', $matches['2'])
    ) {
            // handle different case
            if (empty(trim($matches['1']))) {
                return $matches['1'].'<a href="'.$matches['2'].'">'.$matches['2'].'</a>';
            } else {
                return '<a href="'.$matches['2'].'">'.$matches['1'].'</a>';
            }
    } else {
        return $matches['0'];
    }
}
```

**Comment by remrem** [comment]
Not so bad, I take a look tomorrow.

**Comment by remrem** [comment]
haven't tested but I think your code allow using other URL protocol than http and ftp : 
```
    if (filter_var($matches['2'], FILTER_VALIDATE_URL)
     || preg_match(';^('.join('|', $allowed).');i', $matches['2'])
    ) {
```


Can you try with this ? Allowing use of anchor in article.
```
function markup_clean_href($matches)
{
    // var_dump($matches);
    $allowed = array('http://', 'https://', 'ftp://');
    // if not a valid url, return the string
    if ((
            !filter_var($matches['2'], FILTER_VALIDATE_URL)
         || !preg_match('#^('.join('|', $allowed).')#i', $matches['2'])
        )
     && !preg_match('/^#[\w-_]+$/i', $matches['2']) // allowing [text|#look-at_this]
    ) {
        return $matches['0'];
    }
    // handle different case
    if (empty(trim($matches['1']))){
        return $matches['1'].'<a href="'.$matches['2'].'">'.$matches['2'].'</a>';
    } else {
        return '<a href="'.$matches['2'].'">'.$matches['1'].'</a>';
    }
}
```

**Comment by B4rb3rouss** [comment]
Your version works as expected. Thx!

**Comment by remrem** [comment]
You can push it if you want ;)

**Comment by B4rb3rouss** [comment]
I'm not at home on my personal computer so I can't, you can push it. :)

**Comment by remrem** [comment]
ok
