### ISSUE TITLE
Error on file page afte file deletion

### ISSUE THREAD

**Issue by extragornax** [BlogoText/blogotext#327]
Hello,

Little php error / warning when deleting a file from another page and reloading.
Procedure:
- Browse to the fichiers tab `(admin/fichiers.php)`
- Add a file
- Stay on the page after the upload and open another tab
- Browse to the same url `(admin/fichiers.php)`
- Delete a file from the second tab
- Reload the first one tab

`Notice: Undefined variable: files in /srv/http/blogotext/admin/fichiers.php on line 489

Warning: Invalid argument supplied for foreach() in /srv/http/blogotext/admin/fichiers.php on line 489`

The error is coming from the file existance loop

![sublime_text_2017-10-11_10-53-55](https://user-images.githubusercontent.com/12259540/31430900-80d978e6-ae72-11e7-9973-ae3b121cecaa.png)

**Comment by remrem** [comment]
you working on it or I take a look ?

**Comment by extragornax** [comment]
You can take a look at it if you want, I'm trying to get why we use mebibytes instead of megabytes

**Comment by remrem** [comment]
Ok, I handle this.
"mebibytes" ? Check your lang file ?

**Comment by extragornax** [comment]
![chrome_2017-10-11_11-58-14](https://user-images.githubusercontent.com/12259540/31434139-ccf7e3ee-ae7b-11e7-9f56-dcfc02baddd5.png)
MiB are mebibytes
in french it's the same
![chrome_2017-10-11_12-01-14](https://user-images.githubusercontent.com/12259540/31434168-e6522a66-ae7b-11e7-911b-a76be2401e28.png)

The word is based on
`$maxFileSize = format_size(min(return_bytes(ini_get('upload_max_filesize')), return_bytes(ini_get('post_max_size'))));`

Should I post an issue about it ?

**Comment by remrem** [comment]
My bad, forget about this ... ;)
You want to replace mebi by mega ?

**Comment by extragornax** [comment]
@remrem that's up to you, megabytes seem more logical though

**Comment by extragornax** [comment]
Adding an if statement to check if files exists seems to have fixed the issue.
I'll push an editable PR soon
![sublime_text_2017-10-11_13-44-06](https://user-images.githubusercontent.com/12259540/31438861-42d3d48e-ae8a-11e7-8560-cf9fb480344f.png) @remrem

**Comment by remrem** [comment]
not really, mega is a prefixes (like kilo, giga...) from the SI wich means (x1000), but (every ?) OS use the binary prefixes (1024 and not 1000).    
I think it's a better idea to keep the binary prefixes, it's less mindfuck than Mo, Mo, Mb, MB.     
And you can take a look on [the wikipedia article](https://en.wikipedia.org/wiki/Binary_prefix#Unique_binary_prefixes), seem's the right way to do.

**Comment by extragornax** [comment]
2MB and 2MiB are so similar in size anyway, not an issue

**Comment by extragornax** [comment]
PR #329

**Comment by remrem** [comment]
I think we can close this issue ?

**Comment by extragornax** [comment]
Fixed
