### ISSUE TITLE
[ADDON] Error on addon compliancy version

### ISSUE THREAD

**Issue by extragornax** [BlogoText/blogotext#330]
Addon
If the 'compliancy' version is after the version of the install it gives an error
`Notice: Undefined index: calendar in /srv/http/blogodev/admin/inc/addons.php on line 89`

![chrome_2017-10-12_12-13-44](https://user-images.githubusercontent.com/12259540/31491215-d9e9dd7a-af46-11e7-8180-ef51545bc68e.png)

Error on `$addon = $GLOBALS['addons'][$addon];`
![sublime_text_2017-10-12_12-15-47](https://user-images.githubusercontent.com/12259540/31491285-1e2544fc-af47-11e7-9ccb-8e9cfaa9ab34.png)

Tested with **3.8** as compliancy version on a **3.7.4** install

**Comment by remrem** [comment]
Can you test with branch [fix-330](https://github.com/BlogoText/blogotext/tree/fix-330) ?

**Comment by extragornax** [comment]
@remrem works perfectly
