### ISSUE TITLE
Ajouter des liens dans la sidebar

### ISSUE THREAD

**Issue by qwertygc** [BlogoText/blogotext#337]
Bonjour,
fonctionnalité : ajouter des liens dans la sitebar (genre page de présentation), depuis l'admin.

**Comment by remrem** [comment]
Dans la sidebar du template public ou admin ?

**Comment by qwertygc** [comment]
Sidbar du template public. Usage typique : blogroll, lien vers un article particulier (présentation…). Ceci dit, un plugin peut y faire l'affaire.

**Comment by remrem** [comment]
Yep, un addon pourrait être pas mal ...

**Comment by B4rb3rouss** [comment]
Voilà, j'ai fait un addon, à modifier si besoin : https://github.com/BlogoText/blogotext-addons/pull/38

Il faudrait mettre le code d'intégration dans le thème par défaut.
