### ISSUE TITLE
problème SVG

### ISSUE THREAD

**Issue by qwertygc** [BlogoText/blogotext#339]
Bonjour,
dans admin > fichiers, j'importe un SVG. Impossible d'afficher le SVG en mode général : 

 Warning: getimagesize(): failed to open stream: No such file or directory in admin/fichiers.php on line 354

**Comment by remrem** [comment]
Yep, je viens de check, il y a définitivement un problème avec les paths sur certains fichiers...

**Comment by remrem** [comment]
Peux-tu essayer la branche master, plus particulièrement admin/fichiers.php ?

**Comment by qwertygc** [comment]
👍 impeccable !
