### ISSUE TITLE
Possible to authenticate against another website's mysql?

### ISSUE THREAD

**Issue by poVoq** [BlogoText/blogotext#340]
I have a website running with users stored in a mysql database. Is it possible to link blogotext to these users through a basic sql query?

**Comment by remrem** [comment]
Hi,
Currently no, BlogoText does not support multiple users and the system addons is not used on the admin side.
Over the next few weeks or months, BT will allow multiple users and use addons on the admin side, so maybe it will be possible to write an addon for your needs, but I think it will be a bit more complex than simple mysql query ...

**Comment by remrem** [comment]
I close this issue, if you want this features in the future, we can talk about it after BT 3.8.
