### ISSUE TITLE
[addons] Paramètres de configuration multiples

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#355]
Dans les options disponibles pour un addon, avoir la possibilité de faire un "+" pour ajouter un nouvel élément dans la configuration et récupérer ça sous forme d'array par exemple serait pratique dans certains cas.

**Comment by remrem** [comment]
les addons auront la possibilité d'avoir une page dédiée côté admin, libre au développeur d'un addon d'en créer une et d'y mettre/faire ce qu'il voudra dedans.
Le but de la partie paramètre d'un addon et de faire un formulaire pour les données 'simple'

;)
