### ISSUE TITLE
[addons] : nouveau type de paramètre (code)

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#356]
Dans les paramètres disponibles, on a "text", "int" et "select". 
Avoir un "code" qui serait disponible dans une "textarea" plus grand serait pratique dans certains cas (insertion de code html, écriture d'une page statique...)

**Comment by B4rb3rouss** [comment]
Mini proposition qui consiste en fait à retirer `htmlspecialchar` qui ne sert pas à grand chose dans ce contexte je crois...
Au dev de l'addon de l'utiliser sur les paramètres sensibles, mais pas à appliquer globalement. non ?
https://github.com/BlogoText/blogotext/pull/368

**Comment by B4rb3rouss** [comment]
Ça me va, mais pour ça il faudrait que les paramètres, lorsqu'ils sont
enregistrés, soient traités selon leur type. Or, pour l'instant, ce type
(int, text ou bool) n'est pas distingué. Ou alors, je n'en ai pas vu
mention dans la partie qui récupère les paramètres à enregistrer.

**Comment by remrem** [comment]
à vue de nez dans https://github.com/BlogoText/blogotext/blob/master/admin/inc/addons.php ligne 314 à 344

**Comment by B4rb3rouss** [comment]
ok, j'ai vu, merci. :)
Ça donnerait un truc comme ça, avec le nouveau type "code" que définit le développeur de l'addon s'il tient à autoriser l'insertion de code html.
voilà donc le nouvel essai : 
https://github.com/BlogoText/blogotext/pull/369

**Comment by B4rb3rouss** [comment]
Tu as mergé, merci :)
Je ferme du coup
