### ISSUE TITLE
Liens githubs et bookmarklet

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#361]
Le bookmarklet pour ajouter un lien ne fonctionne pas sur github.

Pour reproduire le bug : 

1. Aller sur l'URL d'un dépot github, au hasard : https://github.com/BlogoText/blogotext
2. Cliquer sur "Save link". Rien ne se passe.

Cependant, ça fonctionne normalement si on ajoute le lien sans passer par le bookmarklet.

Je n'ai pas vraiment creusé plus que ça pour comprendre d'où vient le souci pour l'instant.

**Comment by remrem** [comment]
je jette un coup d'oeil

**Comment by remrem** [comment]
J'ai testé sur 3 plateformes différentes, pas de problème ...

1. Quand tu cliques sur le bookmarklet, tu as bien rediriger vers ton BT ?
2. Si oui, tu peux poster l'url qui te renvoie sur ton BT (vire l'url de dossier admin au besoin) ?    
histoire de voir si l'url est correctement passée en paramètre vers ton BT
3. Si pas de problèmes pour 1 et 2, voir les logs PHP.

**Comment by B4rb3rouss** [comment]
1. Non, et uniquement pour une page github

3. Pas de logs

update : 
Ce message d'erreur apparaît dans la console lorsque je clique sur le bookmarklet : 
```
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« script-src https://assets-cdn.github.com »).
```

**Comment by remrem** [comment]
Ok, j'ai reproduis l'erreur avec firefox en mode privé. Je regarde ça de plus prés.

**Comment by B4rb3rouss** [comment]
Ça vient peut-être d'une extension firefox, mais pour ce qu'on veut faire du bookmarklet ça ne devrait pas.
Rien d'urgent, c'est un bien "maigre" désagrément, mais peut-être le symptôme d'un bug plus gênant.

**Comment by remrem** [comment]
De mémoire, c'est lié aux CORS, du coup, je ne pense pas que l'on puisse faire grand chose ...

**Comment by B4rb3rouss** [comment]
ok, je vais voir de mon côté prochaînement.

**Comment by B4rb3rouss** [comment]
Je voulais voir du côté du bookmarklet de shaarli, mais le [souci est le même](https://shaarli.readthedocs.io/en/master/Bookmarklet/#troubleshooting-the-bookmarklet-doesnt-work-with-a-few-websites-eg-githubcom)

**Comment by B4rb3rouss** [comment]
On doit pouvoir fermer l'issue, puisque ça semble davantage un problème de navigateur qui ne suit pas les spécification qu'un problème blogotext.

**Comment by remrem** [comment]
Vui, mais le problème dure depuis pas mal (trop) de temps. Une solution pourrait être d'écrire des extensions pour les navigateurs. Mais n'ayant pas de retour sur l'utilisation du bookmarklet BT, ni sur le nombre de site ayant des pbs, je ne sais pas si ça vaux le coup de se lancer là dedans ...
