### ISSUE TITLE
Improprement on MySQL config

### ISSUE THREAD

**Issue by extragornax** [BlogoText/blogotext#386]
Allow the user to have no password for the SQL login with a warning message to ask if the box is empty on purpose

**Comment by remrem** [comment]
Or, just put a password on your SQL user account ?
:D

**Comment by extragornax** [comment]
Security is key but in a dev environnent, it's an extra step

**Comment by remrem** [comment]
So do this extra(gornax) step and avoid lowering security as much as possible ;)
