### ISSUE TITLE
Typo in the upload image form

### ISSUE THREAD

**Issue by killruana** [BlogoText/blogotext#389]
The button is labeled "Sens" instead of "Send"

https://github.com/BlogoText/blogotext/blob/dd5eb1c675c4bddc46a17cd9b7f3472a8f0cecbc/admin/inc/lang/en_en.php#L419

**Comment by extragornax** [comment]
Hello,

This issue was already patched. It's already in the dev branch
https://github.com/BlogoText/blogotext/blob/dev/admin/inc/lang/en_en.php#L419

Thanks

**Comment by killruana** [comment]
I didn't see the others branches and I assumed that master is the main development branch.

Sorry for the noise :)

**Comment by extragornax** [comment]
No problem :) 

If you have no other typo to report, you may close the issue

Anyway, thanks for the report, it's always difficult to check everything everywhere
